### ISSUE TITLE
In some cases adding the LicenseHeader to all files in the solution fails with an InvalidOperationException

### ISSUE THREAD

**Issue by FlorianDecker** [rubicon-oss/LicenseHeaderManager#116]
In some cases (seems to happen more regularily with bigger solutions), adding the licenseheader to all files in the solution via the solution context menu throws following exception:

        System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
        at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
        at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
        at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)
        at System.ComponentModel.Container.get_Components()
        at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)
        at LicenseHeaderManager.LicenseHeadersPackage.get_LanguagesPage() in C:\Development\LicenseHeaderManager\LicenseHeaderManager\LicenseHeadersPackage.cs:line 736
        at LicenseHeaderManager.Headers.LicenseHeaderReplacer.TryCreateDocument(ProjectItem item, Document& document, Boolean& wasOpen, IDictionary`2 headers) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\Headers\LicenseHeaderReplacer.cs:line 208
        at LicenseHeaderManager.Headers.LicenseHeaderReplacer.RemoveOrReplaceHeaderRecursive(ProjectItem item, IDictionary`2 headers, Boolean searchForLicenseHeaders) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\Headers\LicenseHeaderReplacer.cs:line 119
        at LicenseHeaderManager.Headers.LicenseHeaderReplacer.RemoveOrReplaceHeaderRecursive(ProjectItem item, IDictionary`2 headers, Boolean searchForLicenseHeaders) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\Headers\LicenseHeaderReplacer.cs:line 178
        at LicenseHeaderManager.PackageCommands.AddLicenseHeaderToAllFilesInProjectCommand.Execute(Object projectOrProjectItem) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\PackageCommands\AddLicenseHeaderToAllFilesInProjectCommand.cs:line 62
        at LicenseHeaderManager.PackageCommands.AddLicenseHeaderToAllFilesInSolutionCommand.AddLicenseHeaderToProjects(List`1 projectsInSolution) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\PackageCommands\AddLicenseHeaderToAllFilesInSolutionCommand.cs:line 141
        at LicenseHeaderManager.PackageCommands.AddLicenseHeaderToAllFilesInSolutionCommand.Execute(Solution solution) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\PackageCommands\AddLicenseHeaderToAllFilesInSolutionCommand.cs:line 77
        at LicenseHeaderManager.ButtonHandler.SolutionLevelButtonThreadWorker.Run(Object solutionObject) in C:\Development\LicenseHeaderManager\LicenseHeaderManager\ButtonHandler\SolutionLevelButtonThreadWorker.cs:line 40

A workaround seems to first remove all license headers and the re-apply them.

This exception is thrown because we are using an pre-async API to access our option pages. To fix this, we should implement our options more like this sample of mads kristensen: https://github.com/madskristensen/OptionsSample

**Comment by suszig** [comment]
same here, i got this error today in the morning :)

**Comment by gkanten** [comment]
I had this issue as well. The removing first and then adding workaround worked for me.

**Comment by mr-j0nes** [comment]
Same error here but I got a different trace (version 3.0.3):

```
System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
   at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)
   at System.ComponentModel.Container.Site.GetService(Type service)
   at System.ComponentModel.Component.GetService(Type service)
   at Microsoft.VisualStudio.Shell.DialogPage.get_SettingsMananger()
   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()
   at LicenseHeaderManager.Options.VersionedDialogPage.LoadSettingsFromStorage() in C:\Build\1776828f99d31c99\LicenseHeaderManager\Options\VersionedDialogPage.cs:line 37
   at Microsoft.VisualStudio.Shell.DialogPage.set_Site(ISite value)
   at System.ComponentModel.Container.Add(IComponent component, String name)
   at System.ComponentModel.Container.Add(IComponent component)
   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)
   at LicenseHeaderManager.LicenseHeadersPackage.get_LanguagesPage() in C:\Build\1776828f99d31c99\LicenseHeaderManager\LicenseHeadersPackage.cs:line 740
   at LicenseHeaderManager.Headers.LicenseHeaderReplacer.TryCreateDocument(ProjectItem item, Document& document, Boolean& wasOpen, IDictionary`2 headers) in C:\Build\1776828f99d31c99\LicenseHeaderManager\Headers\LicenseHeaderReplacer.cs:line 208
   at LicenseHeaderManager.Headers.LicenseHeaderReplacer.RemoveOrReplaceHeaderRecursive(ProjectItem item, IDictionary`2 headers, Boolean searchForLicenseHeaders) in C:\Build\1776828f99d31c99\LicenseHeaderManager\Headers\LicenseHeaderReplacer.cs:line 119
   at LicenseHeaderManager.Headers.LicenseHeaderReplacer.RemoveOrReplaceHeaderRecursive(ProjectItem item, IDictionary`2 headers, Boolean searchForLicenseHeaders) in C:\Build\1776828f99d31c99\LicenseHeaderManager\Headers\LicenseHeaderReplacer.cs:line 178
   at LicenseHeaderManager.PackageCommands.AddLicenseHeaderToAllFilesInProjectCommand.Execute(Object projectOrProjectItem) in C:\Build\1776828f99d31c99\LicenseHeaderManager\PackageCommands\AddLicenseHeaderToAllFilesInProjectCommand.cs:line 62
   at LicenseHeaderManager.PackageCommands.AddLicenseHeaderToAllFilesInSolutionCommand.AddLicenseHeaderToProjects(List`1 projectsInSolution) in C:\Build\1776828f99d31c99\LicenseHeaderManager\PackageCommands\AddLicenseHeaderToAllFilesInSolutionCommand.cs:line 141
   at LicenseHeaderManager.PackageCommands.AddLicenseHeaderToAllFilesInSolutionCommand.Execute(Solution solution) in C:\Build\1776828f99d31c99\LicenseHeaderManager\PackageCommands\AddLicenseHeaderToAllFilesInSolutionCommand.cs:line 64
   at LicenseHeaderManager.ButtonHandler.SolutionLevelButtonThreadWorker.Run(Object solutionObject) in C:\Build\1776828f99d31c99\LicenseHeaderManager\ButtonHandler\SolutionLevelButtonThreadWorker.cs:line 40

```

**Comment by Cloudmersive** [comment]
This software is completely DOA and has been for over a year.  Is this going to get fixed?

**Comment by Stefan-Ilic** [comment]
> 
> 
> This software is completely DOA and has been for over a year. Is this going to get fixed?

Hi @Cloudmersive,

We understand this bug is somewhat annoying. This issue is exacerbated by the fact that we cannot reproduce it realiably at our end. We'll have to look at it eventually when we take on SDK style projects. In the meantime, you or anyone else are more than welcome to provide a PR, we'd be delighted to review and merge it.

Kind regards,
Stefan Ilic
