### ISSUE TITLE
%UserDisplayName% is not expanding to a value

### ISSUE THREAD

**Issue by onpremdiag** [rubicon-oss/LicenseHeaderManager#133]
This was previously working:
Exception caught while trying to lookup the display name with 'UserPrincipal.Current.DisplayName'. 
Stacktrace: System.InvalidCastException: Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' to type 'System.DirectoryServices.AccountManagement.UserPrincipal'.
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.get_Current()
   at LicenseHeaderManager.Headers.UserInfo.TryLookupNow() in C:\Build\1776828f99d31c99\LicenseHeaderManager\Headers\UserInfo.cs:line 83

**Comment by Stefan-Ilic** [comment]
Hi @onpremdiag,

thank you for your report. I was unfortunately unable to reproduce this on my machine. Could you, in addition to the other helpful version information you already provided, tell me which **Windows 10 Version and OS build** you're using? You can look this up under your Windows Settings > System > About. In addition, would you kindly tell me if your user account

* is being administrated through Active Directory (or some other means in your company)
* is based on a Microsoft account
* is just a local account without any ties to a Microsoft account or an administered account

With this information, I'll be able to narrow down my investigations.

Best Regards,
Stefan

**Comment by MichaelKetting** [comment]
see also https://github.com/rubicon-oss/LicenseHeaderManager/issues/97

**Comment by onpremdiag** [comment]
My user account is being administered via AD. This was working previously (no changes that I'm aware of). I have tried with Windows Pin, Windows Hello, and UserID/Password-based authentication. All produce the same result.

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎10/‎7/‎2020
OS build	19042.572
Serial number	004866402157
Experience	Windows Feature Experience Pack 120.2212.31.0

**Comment by Stefan-Ilic** [comment]
Hi @onpremdiag,

I'll get back to you as soon as I get my hands on a Windows 20H2 and can try it out for myself.

Best regards,
Stefan

**Comment by Stefan-Ilic** [comment]
Just to make sure: When you say this was working previously, did you update LicenseHeaderManager at all? Or was it working before you updated to Windows 20H2 and the update broke it?

**Comment by onpremdiag** [comment]
Neither :-(. I'm running the same version of LicenseHeaderManager (3.0.3) on both. Both machines are running the same version of Windows and VS2019.
- Edition	Windows 10 Enterprise
- Version	20H2
- Installed on	‎10/‎7/‎2020
- OS build	19042.572
- Serial number	004866402157
- Experience	Windows Feature Experience Pack 120.2212.31.0

**Comment by Stefan-Ilic** [comment]
Both? Are you saying that you have two PCs with identical Windows versions and VS versions and that LicenseHeaderManager works on one of them but not the other?

When you said that it was working previously, I assumed it worked on _Machine A_ and then suddenly didn't work on _Machine A_ anymore.

**Comment by onpremdiag** [comment]
That is correct:
Machine A (where it works) and Machine B (where it does not work). They _appear_ to be identically configured. I'm seeing a slight difference in behavior on Machine A:
**Working**
![Working](https://user-images.githubusercontent.com/50382987/97333434-91a32700-1849-11eb-8a0c-7e722d63803b.gif)

**Not Working**
![NotWorking](https://user-images.githubusercontent.com/50382987/97334030-37ef2c80-184a-11eb-896d-c3bc704ef47c.gif)

**Comment by pravincar** [comment]
Just ran into the same issue.
My Windows 10 account is managed by an organization. Also I'm logged in via RDP to the Windows machine. Do you have a workaround that you can suggest? Thanks

**Comment by RolandWH** [comment]
# Issue
Hi, I am also having this issue but unlike issue #97 and @onpremdiag it is not expanding to `<unknown>`, it is simply displaying `%UserDisplayName%` in the final file. I am also not getting any kind of an error message. `%UserName%` expands as expected. I am using a local account and it may be worth noting in my case the display name is the same as the username. I am using the extension with a C/C++ console app.

Here is my `projectname.sln.licenseheader` file:
```
extensions: .c .h
/*
 * Filename: %FileName%
 * Author(s): %UserDisplayName% (%UserName%@example.com)
 * Description: Short description of file
 * License: MIT (https://spdx.org/licenses/MIT.html)
*/
```

And here is the header it generates:
```
/*
 * Filename: ceesort.c
 * Author(s): %UserDisplayName% (Roland@example.com)
 * Description: Short description of file
 * License: MIT (https://spdx.org/licenses/MIT.html)
*/
```

# System info
## Software
Windows 10 Enterprise LTSC 2021 (21H2) (Fully updated)
Visual Studio 2022 Community Edition Version 17.2.2 (Latest)

## Hardware
CPU: Ryzen 5 3600 @ 3.6Ghz
RAM: Corsair 16GB (2x8GB) @ 3200Mhz CL14
GPU: AMD RX 5700
Storage: 2TB NVME SSD (PCIe 3), 2TB SATA HDD @ 7200RPM

I am currently just using `%UserName%` as a workaround. Any help on this would be appreciated 😀.
